[Network]
#type rpc or channel
Type="rpc"
#CAFile="ca.crt"
#Cert="sdk.crt"
#Key="sdk.key"
[[Network.Connection]]
#NodeURL="127.0.0.1:20200"
NodeURL="10.211.55.3:8545"
GroupID=1
# [[Network.Connection]]
# NodeURL="127.0.0.1:20200"
# GroupID=2

[Account]
# only support PEM format for now
KeyFile="accounts/0x57695d8ee1c2fd8971a1766e9f2bd036fd14dc9d.pem"

[Chain]
ChainID=1
SMCrypto=false
